# Generated by Django 3.2 on 2021-04-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_inventoryitem_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='extraDetails',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
