# Generated by Django 3.2 on 2021-04-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_inventoryitem_extradetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='lentTo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lentToFriend',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
